object Versions {
    const val androidxAppCompat = "1.6.0"
    const val androidxCore = "1.12.0"
    const val androidxActivity = "1.8.0"
    const val androidxConstraintLayout = "2.1.4"
    const val navigation = "2.7.4"
    const val fragment = "1.6.1"
    const val lifecycleKTX = "2.6.2"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.5"
    const val espressoCore = "3.3.0"
    const val material = "1.10.0"
    const val room = "2.5.0"
    const val koin = "3.5.0"
}
